---
layout: cv
title: Camden Stoker's Resume
editor: 
  markdown: 
    wrap: 72
---

## Contact Info:

\(509\) 714 8210 \| [Email](mailto:stokercamden@gmail.com) \| [Rexburg,
ID](https://www.google.com/maps/place/Rexburg,+ID/@43.8282941,-111.8135115,14z/data=!3m1!4b1!4m6!3m5!1s0x53540a4b807a98b1:0x4a49d8d1d2181c73!8m2!3d43.8231096!4d-111.7924237!16zL20vMHMyYnE?entry=ttu&g_ep=EgoyMDI1MTIwMi4wIKXMDSoASAFQAw%3D%3D)
\| [Linkedin](www.linkedin.com/in/camden-stoker-089384332)

## Education:

Brigham Young University - Idaho Sept 2024 – Spring 2028 (Expected)

Bachelor of Science Major Data Science \| Minor: Business Financial
Analysis

### Relevant Coursework:

-   CSE 110/111 - Python Introduction.
-   CSE 210/211 - C++ with Object-Oriented Programming.
-   DS 250 - Intro to using Python for Data Science and Machine
    Learning.
-   DS 350 - Data Wrangling and Visualization.
-   ITM 110/210 - Database Management and Introduction.
-   ITM 327 - Data Warehousing.

## Key Projects:

Data Science Society Oct 2024 – Apr 2025 \| Clearview Project

Designed and built a PostgreSQL database to manage large datasets for
the Clearview Project. Leveraged database connections through JavaScript
to create a functional, user-facing website.

Data Science Society Apr 2024 – Present \| Property Office Project Lead

Spearheaded a team of six to build a live-updating database and web
interface for a property management system. Utilized PostgreSQL, Python,
HTML, and APIs to ensure real-time data synchronization.

## Experience:

Church of Jesus Christ of Latter-Day Saints\| Missionary\| St. George,
UT\| Aug 2022 – Aug 2024 - Served the Spanish-speaking community during
two years of missionary service. - Collaborated with diverse individuals
to organize and accomplish goals

## Skills:

-   Problem Identification
-   Problem solving
-   High Communication
-   Python
-   R coding language
-   MySQL
-   PostgreSQL
-   Tableau
-   Snowflake
-   Writing dags/API
-   Integrity
-   Caring
-   Growth mindset with criticism

```{=html}
<!-- ### Footer

Last updated: May 2013 -->
```
